In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
print(A.shape)
B= np.array([7, 8])
print(B.shape)
np.dot(A, B)

(3, 2)
(2,)


array([23, 53, 83])

In [5]:
# 86
X = np.array([1.0, 1.5])
W1 = np.array([[0.1, 0.3, 0.5], [00.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(X.shape)
print(W1.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
A1

(2,)
(2, 3)
(3,)


array([0.5, 1.1, 1.7])

In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)
Z1

array([0.62245933, 0.75026011, 0.84553473])

In [16]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
Z2

(3,)
(3, 2)
(2,)


array([0.63783007, 0.79107784])

In [19]:
def identity_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
Y

array([0.32199857, 0.70778016])